import * as mongodb from 'mongodb';

export type PresetModel = {
  _id?: mongodb.ObjectId; // optional because it's generated by MongoDB
  title: string;
  tasks: string[];
};

export type UserModel = {
  _id?: mongodb.ObjectId;
  username: string;
  password: string;
};
